<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>componentDescription</name>
   <tag></tag>
   <elementGuidId>23d9fb4e-5a93-4320-93ee-9c22ba03bd43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@data-e2e-id=&quot;componentDescription&quot;]</value>
   </webElementProperties>
</WebElementEntity>
