<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>defaultAssigne_inputbox</name>
   <tag></tag>
   <elementGuidId>1bb81f36-4c82-4785-8e77-f7d0a54dcdf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;assignee&quot;]/ng-select[@id=&quot;search&quot;]/div/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;assignee&quot;]/ng-select[@id=&quot;search&quot;]/div/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input</value>
   </webElementProperties>
</WebElementEntity>
