<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logs_accordion</name>
   <tag></tag>
   <elementGuidId>b22a0656-39ac-4784-a5fc-935107c1f344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id=&quot;ui-accordiontab-8&quot;]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id=&quot;ui-accordiontab-8&quot;]/span</value>
   </webElementProperties>
</WebElementEntity>
